#ifndef IRC_COMMON_HPP
#define IRC_COMMON_HPP

enum IRC_STATUS
{
		IRC_OK =               200,
		IRC_FORBIDDEN =        403,
		IRC_NOT_FOUND =        404,
		ERR_NONICKNAMEGIVEN =	 431,
		ERR_NICKNAMEINUSE   =	 433,
		ERR_NOTREGISTERED   =	 451,
		ERR_NEEDMOREPARAMS	=	 461,
		ERR_ALREADYREGISTRED = 462,
		IRC_SERVER_ERROR =     500,
		ERR_TOOMANYPARAMS =		 501 //Non Standard.
};

#endif
